input_colour(0,0,black).
input_colour(0,1,black).
input_colour(0,2,black).
input_colour(0,3,black).
input_colour(0,4,black).
input_colour(0,5,black).
input_colour(0,6,black).
input_colour(0,7,black).
input_colour(0,8,black).
input_colour(0,9,black).
input_colour(1,0,black).
input_colour(1,1,black).
input_colour(1,2,black).
input_colour(1,3,black).
input_colour(1,4,black).
input_colour(1,5,black).
input_colour(1,6,black).
input_colour(1,7,black).
input_colour(1,8,black).
input_colour(1,9,black).
input_colour(2,0,black).
input_colour(2,1,black).
input_colour(2,2,black).
input_colour(2,3,black).
input_colour(2,4,black).
input_colour(2,5,black).
input_colour(2,6,black).
input_colour(2,7,black).
input_colour(2,8,black).
input_colour(2,9,black).
input_colour(3,0,black).
input_colour(3,1,black).
input_colour(3,2,black).
input_colour(3,3,black).
input_colour(3,4,black).
input_colour(3,5,black).
input_colour(3,6,black).
input_colour(3,7,black).
input_colour(3,8,black).
input_colour(3,9,black).
input_colour(4,0,black).
input_colour(4,1,black).
input_colour(4,2,black).
input_colour(4,3,black).
input_colour(4,4,black).
input_colour(4,5,black).
input_colour(4,6,black).
input_colour(4,7,black).
input_colour(4,8,black).
input_colour(4,9,black).
input_colour(5,0,black).
input_colour(5,1,black).
input_colour(5,2,grey).
input_colour(5,3,grey).
input_colour(5,4,grey).
input_colour(5,5,black).
input_colour(5,6,grey).
input_colour(5,7,grey).
input_colour(5,8,black).
input_colour(5,9,black).
input_colour(6,0,black).
input_colour(6,1,black).
input_colour(6,2,grey).
input_colour(6,3,black).
input_colour(6,4,black).
input_colour(6,5,black).
input_colour(6,6,black).
input_colour(6,7,grey).
input_colour(6,8,black).
input_colour(6,9,black).
input_colour(7,0,black).
input_colour(7,1,black).
input_colour(7,2,grey).
input_colour(7,3,black).
input_colour(7,4,black).
input_colour(7,5,black).
input_colour(7,6,black).
input_colour(7,7,grey).
input_colour(7,8,black).
input_colour(7,9,black).
input_colour(8,0,black).
input_colour(8,1,black).
input_colour(8,2,grey).
input_colour(8,3,black).
input_colour(8,4,black).
input_colour(8,5,black).
input_colour(8,6,black).
input_colour(8,7,grey).
input_colour(8,8,black).
input_colour(8,9,black).
input_colour(9,0,black).
input_colour(9,1,black).
input_colour(9,2,grey).
input_colour(9,3,grey).
input_colour(9,4,grey).
input_colour(9,5,grey).
input_colour(9,6,grey).
input_colour(9,7,grey).
input_colour(9,8,black).
input_colour(9,9,black).